name: TowerDefense
version: '${project.version}'
main: doodieman.towerdefense.TowerDefense
depend: [HolographicDisplays, Citizens, LuckPerms, WorldGuard, UnikPay]
authors: [DoodieMan]
commands:
  mapsetup:
    aliases: [ setupmap, map ]
    permission: "*"
    permission-message: "§cDet har du ikke adgang til!"
  turretsetup:
    aliases: [ turret, setupturret, towersetup, tower ]
    permission: "*"
    permission-message: "§cDet har du ikke adgang til!"
  setspawn:
    permission: "*"
    permission-message: "§cDet har du ikke adgang til!"
  spawn:
    aliases: [ lobby, leave ]

  admin:
    permission: "*"
  discord:
    aliases: [ discordserver, disc ]
  buy:
    aliases: [butik, store, buycraft]
  staff:
    permission: "staff.staffmode"
    permission-message: "§cDet har du ikke adgang til!"
  tp:
    aliases: [teleport, tpo]
    permission: "staff.teleport"
    permission-message: "§cDet har du ikke adgang til!"
  sc:
    aliases: [staffchat, schat]
    permission: "staff.staffchat"
    permission-message: "§cDet har du ikke adgang til!"