name: TowerDefense
version: '${project.version}'
main: doodieman.towerdefense.TowerDefense
depend: [HolographicDisplays, Citizens, LuckPerms, WorldGuard]
authors: [DoodieMan]
commands:
  mapsetup:
    aliases: [ setupmap, map ]
    permission: "*"
    permission-message: "§cDet har du ikke adgang til!"
  turretsetup:
    aliases: [ turret, setupturret, towersetup, tower ]
    permission: "*"
    permission-message: "§cDet har du ikke adgang til!"
  setspawn:
    permission: "*"
    permission-message: "§cDet har du ikke adgang til!"
  spawn:
    aliases: [ lobby, leave ]

  test:
    permission: "*"
  discord:
    aliases: [ discordserver, disc ]